#加密配置
jasypt:
  encryptor:
    password: elk123

spring:
  redis:
    remote: true        #是否是cachecloud 获取 192.168.99.100
    host: 127.0.0.1
    port: 6379
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
  rabbitmq:
    host: 192.168.1.128
    port: 5672
    username: ENC(1Ehmph15o5VJIayVr90nKQ==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

ribbon:
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  
feign:
#  hystrix:
#    enabled: true
  okhttp:
    enable: true
  httpclient:
    enable: false
#  client:
#    config:
#      feignName:
#        connectTimeout: 30000
#        readTimeout: 30000

#hystrix:
#  threadpool:
#    default:
#      coreSize: 500
#      maxQueueSize: 1000
#      queueSizeRejectionThreshold: 800
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000

#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false