#加密配置
jasypt:
  encryptor:
    password: elk123

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: ENC(r6lx8xL5l+9DWmuMa8t7FA==)
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

ribbon:
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  
feign:
  okhttp:
    enable: true
  httpclient:
    enable: false
    
#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false