server:
  port: 8005

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
    url: jdbc:mysql://192.168.1.80:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    hikari:
      #jdbc-url:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      connection-timeout: 30000
      connection-test-query: SELECT 1
      max-lifetime: 1800000

zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.1.80:5672
      password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
      username: ENC(1Ehmph15o5VJIayVr90nKQ==)
      queue: zipkin
  storage:
    type: mysql