server:
  port: 8003

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ENC(FZ1r4rlIZ+Vdz2ErY26Cow==)
    password: ENC(r6lx8xL5l+9DWmuMa8t7FA==)

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    elk-auth-service:
      path: /auth/**
      serviceId: elk-service-auth
      stripPrefix: true
      sensitiveHeaders:
    elk-upms-service:
      path: /upms/**
      serviceId: elk-service-upms
      stripPrefix: true
      sensitiveHeaders:
  ratelimit:
    key-prefix: elk-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      pig-admin-service:
        limit: 100
        quota: 1
        refresh-interval: 3

security:
  #login:
    #url: /auth/oauth/token
  validate:
      code: false
  sessions: stateless
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://elk-service-auth/user
      prefer-token-info: false
      service-id: elk-platform-zuul

filter:
  urls:
    anon:
      - /auth/**
      - /admin/code/*

logging:
  config: classpath:logback.xml