server:
  port: 8004

spring:
  rabbitmq:
    host: 49.4.21.180
    port: 5672
    username: ENC(Xti+b7Djk0w6BIEzqY3Hiw==)
    password: ENC(ZgaU7KAHGDp0Jzs5TeVxkg==)
  boot:
    admin:
      turbine:
        location: elk-platform-monitor
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream

turbine:
  app-config: elk-platform-zuul #收集监控信息的服务名
  combine-host-port: true
  cluster-name-expression: new String('default') #集群名称