redis:
  cache:
    expiration: 3600


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: elk123
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:  #数据源1
        url: jdbc:mysql://localhost:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      second:  #数据源2
        url: jdbc:mysql://localhost:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          #login-username: admin
          #login-password: admin
      filter:
          stat:
              log-slow-sql: true
              slow-sql-millis: 1000
              merge-sql: true
          wall:
              config:
                  multi-statement-allow: true



mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  typeAliasesPackage: com.elk.cloud.upms.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 1
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true

qiniu:
  accessKey: hM2cBDEM0FTYzpXbigRW90kV12NhhzhFM3jCzurJ
  secretKey: ENC(HM/K0KmtFoZSBhGDEA0Ez71ePTncZlQ954DfLNMZuOftKZq+2WR+dCXH9QEsf768q9wwd92RXLE=)
  bucket: pigcloud
  host: http://p0hpm86wj.bkt.clouddn.com/


logging:
  config: classpath:logback.xml
