server:
  port: 8118

# Redis cache 过期时间设置
redis:
  cache:
    expiration: 60000

# datasoure默认使用JDBC
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
    url: jdbc:mysql://52.83.97.172:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    hikari:
#      #jdbc-url:
#      minimum-idle: 5
#      maximum-pool-size: 50
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#      max-lifetime: 1800000

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# Mybatis配置
mybatis:
  mapperLocations: classpath:/mapper/**/*.xml

swagger:
  basepackage: com.elk.cloud.student.controller #扫描api包路径
  title: Elk APP STUDENT API #API 标题
  description: 小程序学员端 #API描述
  version: 1.0  #版本号
  name: 1.0  #版本号