server:
  port: 8100

elk:
  auth:
    clientId: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
    clientSecret: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
    scope: server

spring:
  rabbitmq:
    host: 49.4.21.180
    port: 5672
    username: ENC(1Ehmph15o5VJIayVr90nKQ==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)

logging:
    config: classpath:logback.xml