server:
  port: 8101

# Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

# datasoure默认使用JDBC
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ENC(+zLZ1qvmUUCbX0vSfi6nqA==)
    url: jdbc:mysql://49.4.21.180:3306/elk_cloud_basis?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  rabbitmq:
    host: 49.4.21.180
    port: 5672
    username: ENC(Xti+b7Djk0w6BIEzqY3Hiw==)
    password: ENC(ZgaU7KAHGDp0Jzs5TeVxkg==)

# Mybatis配置
mybatis:
  mapperLocations: classpath:/mapper/**/*.xml
  configLocation: classpath:mybatis.xml

logging:
  config: classpath:logback.xml