server:
  port: 8005

spring:
  application:
    name: zipkin
  sleuth:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.128:3306/elk_cloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
    schema[0]: classpath:/zipkin.sql
    initialize: true
    continue-on-error: true

zipkin:
  storage:
    type: mysql