server:
  port: 8004

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ENC(FZ1r4rlIZ+Vdz2ErY26Cow==)
    password: ENC(r6lx8xL5l+9DWmuMa8t7FA==)
  boot:
    admin:
      turbine:
        location: elk-platform-monitor
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream

turbine:
  app-config: elk-platform-zuul #收集监控信息的服务名
  combine-host-port: true
  cluster-name-expression: new String('default') #集群名称