server:
  port: 8005

# datasoure默认使用JDBC
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
    url: jdbc:mysql://52.83.97.172:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    hikari:
#      #jdbc-url:
#      minimum-idle: 5
#      maximum-pool-size: 50
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#      max-lifetime: 1800000

zipkin:
  collector:
    rabbitmq:
      addresses: 52.83.103.63:5672
      password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
      username: ENC(4RcC+fEwUkadxvwSE/IEgw==)
      queue: zipkin
  storage:
    type: mysql