server:
  port: 8114

# Redis cache 过期时间设置
redis:
  cache:
    expiration: 60000

spring:
  # 指定静态资源的路径
  resources:
    static-locations: classpath:/static/,classpath:/views/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
    url: jdbc:mysql://192.168.1.128:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    schema[0]: classpath:/activiti.sql
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# Mybatis配置
mybatis:
  mapperLocations: classpath:/mapper/**/*.xml

swagger:
  basepackage: com.elk.cloud.activiti.controller #扫描api包路径
  title: ELK CLOUD SERVICE ACTIVITI #API 标题
  description: PC端流程控制 #API描述
  version: 1.0  #版本号
  name: 1.0  #版本号
