server:
  port: 8100

elk:
  auth:
    clientId: elk
    clientSecret: elk123
    scope: server

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ENC(1Ehmph15o5VJIayVr90nKQ==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)

logging:
    config: classpath:logback.xml