server:
  port: 8107

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8

#logging:
#  level:
#    org:
#      springframework: DEBUG