server:
  port: 8004

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: elk123
  boot:
    admin:
      turbine:
        location: pig-monitor
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream

turbine:
  app-config: elk-cloud-platform-zuul #收集监控信息的服务名
  combine-host-port: true
  cluster-name-expression: new String('default') #集群名称