server:
  port: 8005

# datasoure默认使用JDBC
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
    url: jdbc:mysql://52.83.103.63:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      addresses: 52.83.103.63:5672
      password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
      username: ENC(1Ehmph15o5VJIayVr90nKQ==)
      queue: zipkin
  storage:
    type: mysql