server:
  port: 8100

elk:
  auth:
    clientId: ENC(ZgaU7KAHGDp0Jzs5TeVxkg==)
    clientSecret: ENC(ZgaU7KAHGDp0Jzs5TeVxkg==)
    scope: server

spring:
  rabbitmq:
    host: 49.4.21.180
    port: 5672
    username: ENC(Xti+b7Djk0w6BIEzqY3Hiw==)
    password: ENC(ZgaU7KAHGDp0Jzs5TeVxkg==)

logging:
    config: classpath:logback.xml