#加密配置
jasypt:
  encryptor:
    password: elk123

spring:
  redis:
    remote: true        #是否是cachecloud 获取 192.168.99.100
    host: 127.0.0.1
    port: 6379
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
  rabbitmq:
    host: 192.168.1.91
    port: 5672
    username: ENC(1Ehmph15o5VJIayVr90nKQ==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

ribbon:
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  
feign:
  okhttp:
    enable: true
  httpclient:
    enable: false

#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

# 日志配置
logging:
  config: classpath:logback.xml