server:
  port: 8105
# Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

# datasoure默认使用JDBC
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    password: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    url: jdbc:mysql://49.4.21.180:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  rabbitmq:
    host: 49.4.21.180
    port: 5672
    username: ENC(1Ehmph15o5VJIayVr90nKQ==)
    password: ENC(CxerGjQOXqJ3c+egeJrtIQ==)

# Mybatis配置
mybatis:
  mapperLocations: classpath:/mapper/**/*.xml
  
logging:
  config: classpath:logback.xml