server:
  port: 8108

# Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

# datasoure默认使用JDBC
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(i3W5sWIP+RQt4tt/dk/Qiw==)
    password: ENC(hM6lRkvUkVQTNrU84M9HPvdVhFAL19SoejfmcBkM6Zk00hGh1czoggyxLZjvSmP+)
    url: jdbc:mysql://49.4.21.180:3306/elk_cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull

# Mybatis配置
mybatis:
  mapperLocations: classpath:/mapper/**/*.xml
  configLocation: classpath:mybatis.xml

